version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: demo-docker-nextjs-dev
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    networks:
      - my-network

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-docker-nextjs
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
